### PR TITLE
[Fact Queries] Homework-W2 #2

### PR DESCRIPTION
**Pull request by vzucher**
2nd try pr

### CODE REVIEW

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_2.sql`: 
Dear Student,

Great job on your homework submission! You've done a good job of following the prompt and your code is well-structured and easy to read. Here are some specific points of feedback:

1) **Coverage of the Homework Prompt:** Your code covers most aspects of the homework prompt. You've correctly joined the `devices` and `web_events` tables, and you've included the `user_id` and `browser_type` columns. However, the prompt asked for a DDL statement to create the `user_devices_cumulated` table, but your code is a DML statement that creates and populates the table in one go. You might want to separate these into two steps: first, create the table with the correct schema, and then populate it with data.

2) **Logical Flow:** Your approach to the problem is logical and coherent. You've correctly used a CTE to join the `devices` and `web_events` tables, and you've used the `ARRAY_AGG` function to create the `dates_active` array. However, the prompt asked for the first index of the date list array to correspond to the most recent date, but your code doesn't ensure this. You might want to order the dates in descending order before aggregating them.

3) **Readability:** Your code is well-formatted and easy to read. You've used meaningful variable names and included comments explaining your thought process, which is great. However, the last comment about grouping by `device_id` seems unrelated to the rest of the code and might be confusing to others reading your code.

4) **Robustness and Error Handling:** Your code doesn't include any error handling or checks for invalid inputs. While this might not be necessary for this specific assignment, it's a good habit to get into, especially when working with real-world data.

5) **Modularity and Reusability:** Your code is fairly modular and could be easily adapted to similar problems. However, by separating the DDL and DML statements, you could make your code even more reusable.

Here's an example of how you might modify your code based on this feedback:

```sql
-- Create the table
CREATE TABLE user_devices_cumulated (
  user_id BIGINT,
  browser_type VARCHAR,
  dates_active ARRAY(DATE),
  date DATE
) WITH (
  format = 'parquet',
  partitioning = array['date']
);

-- Populate the table
INSERT INTO user_devices_cumulated
SELECT
    user_id,
    browser_type,
    ARRAY_AGG(event_date ORDER BY event_date DESC) AS dates_active, -- Order dates in descending order
    MAX(event_date) AS date
FROM
    CombinedData
GROUP BY
    user_id, browser_type;
```

Keep up the good work!

Best,
[Your Name]

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_5.sql`: 
Hi there,

Great job on your homework submission! You've done a good job of following the homework prompt and your SQL syntax is correct. Here are a few points of feedback:

1) **Coverage of the homework prompt:** Your code covers all aspects of the homework prompt. You've correctly created the `hosts_cumulated` table with the required fields: `host`, `host_activity_datelist`, and `date`.

2) **Logical flow:** Your solution logically follows the given homework prompt. The structure of your SQL statement is correct and coherent with the information provided in the prompt.

3) **Readability:** Your code is very readable. You've used meaningful variable names and included comments explaining your thought process, which is excellent. The overall formatting of your code is also good, making it easy to understand.

4) **Robustness and error handling:** As this is a DDL statement, there's not much scope for error handling or dealing with edge cases. However, it's always a good practice to consider these aspects in your code. In future, when writing more complex SQL queries or scripts, consider how your code might handle unexpected or invalid inputs.

5) **Modularity and reusability:** Your code is well-structured and could easily be reused in other contexts. The `CREATE OR REPLACE TABLE` statement you've used is a good choice, as it allows for the table to be easily updated or replaced in the future.

One minor point to note is that the example solution includes a `metric_name` and `metric_value` field, which are not included in your table. These fields are not required by the homework prompt, but you might find them useful in future if you want to store different types of metrics for each host.

Keep up the good work!

**Review by thyanhbui1412 — CHANGES_REQUESTED** [review]
I don't see a query to populate data into host_activity_reduced.

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_1.sql`: 
Hi,

Great job on your homework submission! Your SQL query correctly de-duplicates the `nba_game_details` table based on the combination of `game_id`, `team_id`, and `player_id`. You've used the `ROW_NUMBER()` window function effectively to assign a unique row number to each row within a partition of `game_id`, `team_id`, and `player_id`, and then filtered to only include the first row of each partition. This is a good approach to solving the problem.

Here are a few suggestions for improvement:

1. **Readability and Comments:** Your code is well-structured and easy to read. However, it would be beneficial to include comments in your code to explain your thought process and what each part of the code does. This will make it easier for others (and future you) to understand your code.

2. **Ordering in ROW_NUMBER():** In your `ROW_NUMBER()` function, you've used `ORDER BY game_id`. However, since you're partitioning by `game_id`, `team_id`, and `player_id`, the `ORDER BY` clause doesn't have any effect. You could consider removing it to simplify your code.

3. **Selecting All Columns:** In your CTE, you've listed all the columns individually. While this is not wrong, it can be simplified by using `*` to select all columns, like in the example solution. This can make your code cleaner and easier to maintain, especially when dealing with tables that have many columns.

4. **Error Handling and Robustness:** Your code does a good job of handling the task at hand. However, it's always a good idea to think about potential edge cases or errors that could occur. For example, what if there are null values in the `game_id`, `team_id`, or `player_id` columns? How would your code handle that? It might be worth adding some error handling or checks for these kinds of scenarios.

Keep up the good work!

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_2.sql`: 
Hi there,

Great job on your homework submission! You've done a good job of following the homework prompt and your code is well-structured and easy to read. Here are some specific points of feedback:

1) **Coverage of the Homework Prompt:** Your code covers all aspects of the homework prompt. You've correctly created the `user_devices_cumulated` table with the correct columns and data types as specified in the prompt. You've also correctly specified the table format as 'PARQUET' and partitioned the table by 'date', which is exactly what was asked for in the prompt.

2) **Logical Flow:** Your solution logically follows the given homework prompt. The structure of your code is clear and coherent, and it aligns well with the information provided in the prompt.

3) **Readability:** Your code is very readable. You've used meaningful variable names that align with the prompt, and your code is well-formatted and easy to follow. However, it would be beneficial to include comments in your code to explain your thought process and make it even easier for others to understand.

4) **Robustness and Error Handling:** As this is a DDL statement, there isn't much scope for error handling or dealing with edge cases. However, it's always a good idea to consider these aspects in your code. For example, you could consider what would happen if the `user_id` or `browser_type` were null, or if the `dates_active` array was empty.

5) **Modularity and Reusability:** Your code is modular and could easily be reused in other contexts. The creation of the `user_devices_cumulated` table is a common task in data engineering, and your code could be used as a template for similar tasks in the future.

Overall, you've done a great job on this assignment. Keep up the good work!

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_3.sql`: 
Dear Student,

Great job on your SQL homework submission! Your code is well-structured, and your comments are clear and helpful in understanding your thought process. Here are some points I would like to highlight:

1) **Homework Prompt Coverage:** Your code covers all aspects of the homework prompt. You have correctly implemented the incremental query to populate the table from the `web_events` and `devices` tables. The use of Common Table Expressions (CTEs) for 'yesterday' and 'today' is a good approach.

2) **Logical Flow:** Your solution logically follows the given homework prompt. The structure of your code is coherent, and the use of CTEs makes it easy to follow the logic of your query.

3) **Readability:** Your code is very readable. You have used meaningful variable names and included comments explaining your thought process. The overall formatting of your code is also good, which makes it easy to read and understand.

4) **Robustness and Error Handling:** Your use of the `COALESCE` function to handle null values is a good practice. However, your code does not handle the case where there are no records for 'yesterday' or 'today'. You might want to add some error handling or checks to ensure that your code can handle these edge cases.

5) **Modularity and Reusability:** Your code is modular and can be easily reused in other contexts. The use of CTEs makes your code more modular and easier to understand.

One suggestion for improvement would be to replace the hard-coded dates with a dynamic date calculation. This would make your code more flexible and reusable. For example, you could replace `DATE '2021-02-04'` with a function that calculates the date of the last record in the `user_devices_cumulated` table.

Keep up the good work!

Best,
[Your Name]

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_4.sql`: 
Hi,

Great job on your homework submission! You've done a good job of following the prompt and your code is well-structured and easy to follow. Here are some specific points of feedback:

1) **Coverage of the homework prompt:** Your code covers all aspects of the homework prompt. You've successfully converted the date list implementation into the base-2 integer datelist representation. You've also correctly implemented the three main transformations required for this task.

2) **Logical flow:** Your solution logically follows the given homework prompt. The use of CTEs (Common Table Expressions) makes your code easy to follow and understand. Each step of the transformation process is clearly defined and executed.

3) **Readability:** Your code is very readable. You've used meaningful variable names and included detailed comments explaining each step of your process. This makes your code easy to understand and follow.

4) **Robustness and error handling:** Your code seems robust and should handle the given inputs well. However, it's always a good idea to include some error handling or checks for potential issues. For example, you could add checks to ensure that the `dates_active` array is not null or empty before trying to use it.

5) **Modularity and reusability:** Your code is modular and should be relatively easy to reuse in other contexts. The use of CTEs helps to separate different parts of the process, making it easier to understand and modify if needed.

One suggestion for improvement would be to avoid hardcoding dates in your query. Instead, you could use a variable or a function to dynamically generate the date range. This would make your code more flexible and reusable.

Overall, great work! Keep it up.

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_5.sql`: 
Hi,

Great job on your homework submission! Your SQL DDL statement is well-structured and logically follows the given homework prompt. Here are some specific points of feedback:

1) **Coverage of the Homework Prompt:** Your code covers all aspects of the homework prompt. You have correctly defined the `hosts_cumulated` table with the required fields: `host`, `host_activity_datelist`, and `date`. You have also correctly specified the storage format as 'PARQUET' and partitioned the table by the 'date' column.

2) **Code Readability:** Your code is very readable. You have used meaningful variable names and included detailed comments explaining your thought process. This makes it easy for others to understand your code. Keep up the good work!

3) **Robustness and Error Handling:** As this is a DDL statement, there isn't much scope for error handling. However, you have used the `CREATE OR REPLACE TABLE` statement, which is a good practice as it ensures that the table will be created if it does not exist, or replaced if it does.

4) **Modularity and Reusability:** Your code is modular and can be easily reused in other contexts. The structure of your DDL statement is standard and can be adapted to create other tables with similar requirements.

One minor point to note is that the example solution includes two additional fields: `metric_name` and `metric_value`. These fields are not required by the homework prompt, but you might want to consider whether they could be useful in your table, depending on the specific use case.

Overall, excellent work! Keep it up.

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_6.sql`: 
Dear Student,

Great job on your homework submission! Your solution is well-structured and logically follows the given homework prompt. You've done a good job of incrementally populating the `hosts_cumulated` table from the `web_events` table. 

Here are some points of feedback:

1) **Coverage of the Homework Prompt:** Your solution covers most aspects of the homework prompt. However, the prompt asks for a query to incrementally populate the `hosts_cumulated` table, but your solution seems to be populating the table for the current day only. You might want to consider a solution that can handle incremental updates for any given day, not just the current day.

2) **Code Readability:** Your code is well-commented, which makes it easier to understand your thought process. The use of Common Table Expressions (CTEs) also enhances readability by breaking down the query into smaller, more manageable parts. However, the indentation of your code could be improved for better readability. For example, the `previous_activity` CTE could be indented to align with the `today_activity` CTE.

3) **Robustness and Error Handling:** Your solution seems to handle edge cases well, especially with the use of `COALESCE` to handle potential NULL values. However, it's not clear how your solution would handle invalid inputs or potential errors. You might want to consider adding some error handling or input validation to your solution.

4) **Modularity and Reusability:** Your solution is modular and reusable, thanks to the use of CTEs. However, you might want to consider parameterizing your query to make it even more reusable. For example, you could replace `CURRENT_DATE` with a variable so that the query can be used for any given date.

Overall, you've done a good job on this assignment. Keep up the good work!

Best,
[Your Name]

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_7.sql`: 
Hi,

Great job on your homework submission! Your SQL DDL statement correctly creates the `host_activity_reduced` table with the required fields: `host`, `metric_name`, `metric_array`, and `month_start`. Your code is well-structured and logically follows the given homework prompt.

Here are a few points of feedback:

1) **Readability:** Your code is very readable, and I appreciate the detailed comments you've included. They provide a clear explanation of what each line of code does, which is very helpful for anyone who might need to understand or maintain this code in the future.

2) **Robustness and Error Handling:** In this case, the robustness and error handling are largely handled by the SQL engine itself. However, it's always a good idea to consider potential issues that could arise. For example, you might want to consider adding constraints to ensure that the `host`, `metric_name`, and `month_start` fields are not null.

3) **Modularity and Reusability:** Your code is well-structured and could easily be adapted to create similar tables in the future. One suggestion for further improving the reusability of your code would be to parameterize the table name and field names, so that the same code could be used to create different tables with a similar structure.

Overall, you've done an excellent job on this assignment. Keep up the good work!

**Comment by julie-scherer** [comment]
This is a LLM-generated comment for `query_8.sql`: 
Dear Student,

Great job on your homework submission! You've done a good job of following the prompt and your code is generally well-structured and readable. Here are some specific points of feedback:

1) **Coverage of the Homework Prompt:** Your code covers most aspects of the homework prompt. You've correctly used a full outer join and handled imputing empty values in the array for windows where a host gets a visit in the middle of the array time window. However, the prompt asked you to incrementally populate the `host_activity_reduced` table from a `daily_web_metrics` table, but you've created your own `daily_web_metrics` within the query. This might not be a problem if your `daily_web_metrics` matches the one in the prompt, but it's something to be aware of.

2) **Logical Flow:** Your solution logically follows the given homework prompt. You've correctly used a full outer join to combine the data from the `yesterday` and `today` tables, and you've handled the case where a host gets a visit in the middle of the array time window.

3) **Readability:** Your code is generally well-formatted and easy to read. You've used meaningful variable names and included comments to explain your thought process. However, the `CASE` statement in the `daily_web_metrics` CTE could be simplified for better readability. Instead of repeating the `CASE` statement in the `GROUP BY` clause, you could assign the result of the `CASE` statement to a variable in the `SELECT` clause and then use that variable in the `GROUP BY` clause.

4) **Robustness and Error Handling:** Your code seems to handle edge cases and invalid inputs well. You've used the `COALESCE` function to handle null values, and you've used a `CASE` statement to handle different URLs. However, it's not clear how your code would handle a situation where the `url` is not `'/'` or `'/signup'`. You might want to add an `ELSE` clause to your `CASE` statement to handle other URLs.

5) **Modularity and Reusability:** Your code is modular and could be easily adapted for other similar tasks. The `daily_web_metrics`, `yesterday`, and `today` CTEs could be reused in other queries with minor modifications.

Overall, you've done a good job on this assignment. Keep up the good work!

Best,
[Your Name]

**Pull request closed without merging**
